### ISSUE TITLE
tests: List with ListModePart should be on specific path

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#1000]
https://github.com/beyondstorage/go-storage/blob/58e73a0d974c9b95a6ff8ff3d47b1f25c4cfb033/tests/multiparter.go#L246-L249

We need to use `store.List(path, pairs.WithListMode(types.ListModePart))` here.

**Comment by Joey-1445601153** [comment]
Fixed by https://github.com/beyondstorage/go-storage/pull/1010.

**Comment by Xuanwo** [comment]
@Joey2132, instead of add comment `Fixed by #1010.` here, you can say `Fixed #1000` in #1000.
