### ISSUE TITLE
services/s3: While ListMode is ListModeDir,  we need to add suffix under path

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#1018]

**Comment by JinnyYi** [comment]
In [byctl](https://github.com/beyondstorage/beyond-ctl), we implemented `ls` command through `List` with `ListModeDir`. After adding suffix under path for `List` with `ListModeDir`, we can't get the objects without the `/` prefix in the object name.

**Comment by Xuanwo** [comment]
https://github.com/beyondstorage/go-storage/blob/813c8a192cfc9f43eac39d66a910cf8d6512b7ec/services/s3/storage.go#L272-L275

I think it's a bug that introduced in this commit. Instead, we need to update `path` before `s.getAbsPath(path)`.

**Comment by Xuanwo** [comment]
ping @Joey2132, can you also fix this problem for s3?

**Comment by Joey2132** [comment]
> ping @Joey2132, can you also fix this problem for s3?

Got it. I will do it soon.
