### ISSUE TITLE
tests: Migrate all tests to Feature and suite based

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#1022]
## Background

For now, our tests are using `convey` to write BDD test. However, they could be much simpler if we write them using `github.com/stretchr/testify/suite`.

Here is an example: https://github.com/beyondstorage/go-storage/pull/1020

**Comment by Joey2132** [comment]
So, actually before I handle issue 975, this issue has to be finished first. Is anyone doing it now? If not, I'd like to do it.

**Comment by Xuanwo** [comment]
The issue is free for you to take! However, I think it's better to finish #975 before take on this issue.

**Comment by Joey2132** [comment]
> The issue is free for you to take! However, I think it's better to finish #975 before take on this issue.

In old  version, it will not use feature to judge whether tests that are not supported should be skipped.
For example, azblob just doesn't support `CommitAppend` operation. Integration test will fail at [tests/appender.go#65](https://github.com/beyondstorage/go-storage/blob/master/tests/appender.go#L65).

**Comment by Joey2132** [comment]
> The issue is free for you to take! However, I think it's better to finish #975 before take on this issue.

OK, I will finish #975 first.
