### ISSUE TITLE
go-storage documentation page not found

### ISSUE THREAD

**Issue by ceyhunkerti** [beyondstorage/go-storage#1119]
go-storage documentation on `beyondstorage.io` yields page not found

[beyondstorage.io](https://beyondstorage.io/docs/go-storage/index)

![image](https://user-images.githubusercontent.com/6328046/151655772-df7bc380-7ad3-4078-b410-09d212a6a097.png)

**Comment by xxchan** [comment]
Temporary fix: Removing `index` can find it: https://beyondstorage.io/docs/go-storage

**Comment by xxchan** [comment]
Website also fixed now (do not link to pages end with `/index`) https://github.com/beyondstorage/site/pull/280
