### ISSUE TITLE
Implement AOS-61 Add object mode check for operations

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#557]
Maybe we can add this check in code generation?

**Comment by Prnyself** [comment]
Need implementation in these services:
- [ ] s3
- [ ] gcs
- [ ] azblob
- [ ] oss
- [ ] qingstor
- [ ] fs
- [ ] dropbox
- [ ] cos
- [ ] kodo
- [ ] uss

**Comment by Xuanwo** [comment]
ref: https://github.com/aos-dev/go-service-qingstor/pull/48

**Comment by Xuanwo** [comment]
@Prnyself please keep tracking on the implementations.

**Comment by Prnyself** [comment]
> @Prnyself please keep tracking on the implementations.

I will update every ref after the PR merged.
