### ISSUE TITLE
Tracking Issue for GSP-127: Add ServiceInternel and RequestThrottled Errors

### ISSUE THREAD

**Issue by xxchan** [beyondstorage/go-storage#612]
[proposal](https://github.com/beyondstorage/specs/blob/master/rfcs/127-add-serviceinternel-and-requestthrottled-errors.md)

- [x] https://github.com/beyondstorage/go-storage/pull/616 Add the error codes in go-storage.
- [x] https://github.com/beyondstorage/site/pull/138 Add them in the doc.

**Comment by Xuanwo** [comment]
Thanks to @junaire 's contribution, GSP-127 has been implemented. Our services can use `ErrServiceInternel` and `ErrRequestThrottled` now.
