### ISSUE TITLE
Tracking issue for GSP-134: Write Behavior Consistency

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#624]
- [Rendered GSP](https://github.com/beyondstorage/specs/blob/master/rfcs/134-write-behavior-consistency.md)

## Steps

- [x] #625
- [x] https://github.com/beyondstorage/go-storage/pull/656
- [x] https://github.com/beyondstorage/go-integration-test/pull/32

## Related issues

This issue will solve following discussions, close them for now.

- https://github.com/beyondstorage/specs/issues/130
- https://github.com/beyondstorage/specs/issues/96
- https://github.com/beyondstorage/go-integration-test/issues/29

**Comment by Xuanwo** [comment]
This issue will solve following discussions, close them for now.

- [Add detailed behavior about move/copy](https://github.com/beyondstorage/specs/issues/130)
- [Make write Idempotent](https://github.com/beyondstorage/specs/issues/96)
- [copy/move doesn't need to support dst path that has an existing path](https://github.com/beyondstorage/go-integration-test/issues/29)

**Comment by xxchan** [comment]
Should add a subtask for integration tests?
