### ISSUE TITLE
Idea: Notification (CDC) Support

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#633]
Our Storage Service may support sending notifications to let users get the changes of storage. 

This feature likes CDC(Change Data Capture) for DBMS.

We may need to:

- Define Change/Event struct that fit all storage services need
  - S3 Notification
     - https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html
  - Filesystem
     - [inotify](https://man7.org/linux/man-pages/man7/inotify.7.html)
     - use eBPF to capture changes.
       - https://github.com/cilium/ebpf ?
- Support different event receiver
  - Work as a webhook?
  - Message Queue?

**Comment by xxchan** [comment]
Here's a (not verified) table of storage event types. We can see that they vary a lot:
1. Different services have different advanced feature, e.g., download for s3, metadata update for gcs, abort_multipart for qingstor. If we omit them, the most basic and common events are only create & delete.
2. Only half of the services support fine-grained event types.
3. There's inconsistent behaviour: e.g., oss counts `InitiateMultipartUpload` & `UploadPart` as create event, while s3 and cos don't.

So I think this means that storage event is highly service-related and thus it is hard to provide a comprehensive unified event format. 

|                   |                                       | oss  | s3   | cos  | gcs  | qingstor | azblob |
| ----------------- | ------------------------------------- | ---- | ---- | ---- | ---- | -------- | ------ |
| ObjectCreated     | *                                     |      | √    | √    | √    | √        | √      |
|                   | ObjectCreated:PutObject               | √    | √    | √    |      |          |        |
|                   | ObjectCreated:PostObject              | √    | √    | √    |      |          |        |
|                   | ObjectCreated:CopyObject              | √    | √    | √    |      |          |        |
|                   | ObjectCreated:InitiateMultipartUpload | √    |      |      |      |          |        |
|                   | ObjectCreated:UploadPart              | √    |      |      |      |          |        |
|                   | ObjectCreated:UploadPartCopy          | √    |      |      |      |          |        |
|                   | ObjectCreated:CompleteMultipartUpload | √    | √    | √    |      | √        |        |
|                   | ObjectCreated:AppendObject            | √    |      | √    |      |          |        |
| ObjectDownloaded  | ObjectDownloaded:GetObject            | √    |      |      |      |          |        |
| ObjectRemoved     | *                                     |      | √    | √    | √    | √        | √      |
|                   | ObjectRemoved:DeleteObject            | √    |      |      |      |          |        |
|                   | ObjectRemoved:DeleteObjects           | √    |      |      |      |          |        |
|                   | version delete                        |      | √    | √    | √    |          |        |
| ObjectReplication | *                                     |      |      |      |      |          |        |
|                   | ObjectReplication:ObjectCreated       | √    |      |      |      |          |        |
|                   | ObjectReplication:ObjectRemoved       | √    |      |      |      |          |        |
|                   | ObjectReplication:ObjectModified      | √    |      |      |      |          |        |
|                   | OperationFailedReplication            |      | √    |      |      |          |        |
| metadata update   |                                       |      |      |      | √    |          |        |
| abort_multipart   |                                       |      |      |      |      | √        |        |

**Comment by xxchan** [comment]
The APIs of configuring notification are similar (but `oss` does not have this API!). Params are: bucket name, event (type, filter, id, arn). The most tricky thing is event type. It seems hard to give a global event type (like global pairs)

**Comment by Xuanwo** [comment]
Another thing I found out is that some services (like s3) only support sending events to internal services like Amazon SNS, Amazon SQS, or AWS Lambda.

**Comment by xxchan** [comment]
> Another thing I found out is that some services (like s3) only support sending events to internal services like Amazon SNS, Amazon SQS, or AWS Lambda.

Actually only qingstor supports HTTP endpoint directly.

**Comment by xxchan** [comment]
And it seems to be encouraged to configure notification in the console instead of using API 🤔

**Comment by Xuanwo** [comment]
So we now have two difficulties.

- The event types are so different that it is impossible to abstract to a uniform event type
- the service itself does not support sending events to a specific http endpoint

**Comment by xxchan** [comment]
For the second problem, my previous idea is to use SNS as a middle station, and add an HTTP endpoint subscription to the SNS topic. If so, the user will have to also provide the SNS arn besides HTTP endpoint.

**Comment by Xuanwo** [comment]
> If so, the user will have to also provide the SNS arn besides HTTP endpoint.

But SNS arn is also very different between services?

**Comment by xxchan** [comment]
> Can we create SNS for user?

some quick results (whether have CreateTopic API):
- AWS SNS: ok
- google Pub/Sub: not (gcloud cli tool/console)
- aliyun MNS: ok (but no oss notification API)

**Comment by xxchan** [comment]
> But SNS arn is also very different between services?

Not sure. Example:
- AWS TopicArn: arn:aws:sns:us-east-2:123456789012:MyTopic
- gcs notificationConfigs   "topic": "projects/PROJECT_ID/topics/TOPIC_NAME"

My previous concern was that if the user will go to the console to create a topic, why doesn't he just continue to configure the notification there? So "Can we create SNS for user?" is a problem.

**Comment by Xuanwo** [comment]
*Let's discuss event type later, it's a bit simpler.*

> My previous concern was that if the user will go to the console to create a topic, why doesn't he just continue to configure the notification there? So "Can we create SNS for user?" is a problem.

So there are two methods:

- API that accepts the dst endpoint: that means we need to create an SNS service for the user if the service doesn't have native support.
- API that accepts service internal ARN (in a plain string): that means the user needs to create SNS service by themself.

**Comment by Xuanwo** [comment]
Maybe related to #634

**Comment by xxchan** [comment]
Is creating a service **implicitly** acceptable to users? One thing is that it involves billing.

**Comment by Xuanwo** [comment]
> So there are two methods:
> 
>     * API that accepts the dst endpoint: that means we need to create an SNS service for the user if the service doesn't have native support.
> 
>     * API that accepts service internal ARN (in a plain string): that means the user needs to create SNS service by themself.

For method 1: I agree with your concern, it's not acceptable.
For method 2: It looks meaningless for users (why not config them in console directly?)

Maybe it's out of our scope to implement the notification config API (And we don't have the ability for it), let's wipe them out.

---

Without the notification API support, do you think it still useful to implement a global event struct type?

**Comment by xxchan** [comment]
I think users may write this themselves with few lines of code and won't try to find a simple library to do so.

**Comment by Xuanwo** [comment]
Let's mark this idea as a backlog, and drop it for now, thanks to your research!

**Comment by Xuanwo** [comment]
How about implement CDC via scanning? Like rockset does: https://rockset.com/blog/change-data-capture-what-it-is-and-how-to-use-it/
