### ISSUE TITLE
Allow generate signed url for upload objects

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#646]
We provide an API `Reach` for generating an URL for an object for the user to get.

Maybe we can provide like `Reach` but for uploading an object.

**Comment by Xuanwo** [comment]
How about add API like:

```go
type Accessor interface {
    func Access(op, path string, pairs...) (req *http.Request, err error)
}
```

**Comment by JinnyYi** [comment]
We can implement it as most object support `SignedURL`.

For `Accessor`, I have two other doubts：
- What's the difference between `Reach()` and `AccessRead()`? Both of them are used for reach an object, maybe `AccessRead()` is not needed?
- If the service only support `AccessRead()`, like `kodo`, does it mean we can't implement `Accessor` for it?

**Comment by Xuanwo** [comment]
Our users have a need to support the generation of a signed URL that allows their end-users to upload/download the corresponding data directly.

Operations that they need include: (take S3 as an example)

- PutObject
- GetObject
- CreateMultipart
- WriteMultipart
- CompleteMultipart

**Comment by Xuanwo** [comment]
Hi, I camp up a new idea that, we can define a new interface like:

```go
type HttpSinger interface {
    QuerySignHttp(req *http.Request, ps ...types.Pair) (req *http.Request, query string, err error)
//    HeaderSignHttp(req *http.Request, ps ...types.Pair) (req *http.Request, auth string, err error)
}
```

For now, `HeaderSignHttp` is not required, we can add them later.

**Comment by JinnyYi** [comment]
`QuerySignHttp(req *http.Request, ps ...types.Pair) (signedReq *http.Request, url string, err error)` is indeed more universality. We can generate request's signed URL in `QuerySignHttp`.

As external methods are provided for obtaining signed URL for most services, maybe the parameter `req *http.Request` complicates matters：
- Users need to pass in the `req.URL` correctly.
- We need to parse `req.URL` to get the wanted request resource(operation, path...).

How about one of the following methods：
 - `QuerySignHttp(op path string, ps ...types.Pair) (signedReq *http.Request, err error)`
 - `QuerySignHttp(req *Request, ps ...types.Pair) error`
    ```
    type Request struct {
        Name        string  // "GetObject"
        HTTPPaht    string  // "{Key+}"
        HTTPRequst  *http.Request
        ...
    }
    ```

**Comment by Xuanwo** [comment]
```go
req, err := store.QuerySignHttp(types.OpRead, "abc")

req, err := store.QuerySignHttp(types.OpWrite, "abc", pairs.WithContentType("application/json"))

req, err := store.QuerySignHttp(types.OpWriteMultipart, "abc", pairs.WithMultipartId("qqqq"))
```

Looks nice.

**Comment by JinnyYi** [comment]
> ```go
> req, err := store.QuerySignHttp(types.OpRead, "abc")
> 
> req, err := store.QuerySignHttp(types.OpWrite, "abc", pairs.WithContentType("application/json"))
> 
> req, err := store.QuerySignHttp(types.OpWriteMultipart, "abc", pairs.WithMultipartId("qqqq"))
> ```

I will continue the GSP based on this.
