### ISSUE TITLE
v4.3.0 Release Roadmap

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#663]
Let's start to release the v4.3.0!

**Comment by Xuanwo** [comment]
Maybe it's better to add workflow like https://github.com/beyondstorage/go-service-s3/blob/master/.github/workflows/go-storage-auto-build.yml into service before we release new versions?

**Comment by JinnyYi** [comment]
> Maybe it's better to add workflow like https://github.com/beyondstorage/go-service-s3/blob/master/.github/workflows/go-storage-auto-build.yml into service before we release new versions?

Do services in alpha state need to add the workflow? The same with go-integration-test,  go-service-example, go-storage-example, go-coreutils.

**Comment by Xuanwo** [comment]
> Do services in alpha state need to add the workflow?

I think we need it.

> The same with go-integration-test, go-service-example, go-storage-example, go-coreutils.

`go-service-example`  need, but others not.
