### ISSUE TITLE
Tracking issue of GSP-669: Feature Lifecycle

### ISSUE THREAD

**Issue by xxchan** [beyondstorage/go-storage#672]
[PR](https://github.com/beyondstorage/go-storage/pull/669)

https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/669-feature-lifecycle.md

## Implementation

- Implement an automated tool to create tracking issues for all the services.
- Implement CI to let dependabot run `go-storage` code generator automatically.

**Comment by Xuanwo** [comment]
Commit pushed by actions will not trigger new workflow run, I will fix it.

**Comment by Xuanwo** [comment]
It works, I will update all workflows tomorrow. https://github.com/beyondstorage/go-service-kodo/pull/42

**Comment by Xuanwo** [comment]
ping @JinnyYi , we need to release all services that upgraded to v4.3.2

**Comment by JinnyYi** [comment]
> ping @JinnyYi , we need to release all services that upgraded to v4.3.2

Got it.
