### ISSUE TITLE
Remove not used package in service.tmpl

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#677]
It looks like we don't need `credential.Provider` anymore, we can remove the import:

```go
"github.com/beyondstorage/go-storage/v4/pkg/credential"
```

## Steps

- [ ] Remove the import from `cmd/definitions/tmpl/service.tmpl`
- [ ] `make build` to trigger generation

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by Xuanwo** [comment]
> I would like to take this one.

Great, I've assigned this issue to you and look forward to your PR!
