### ISSUE TITLE
Oracle Cloud Storage Service

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#692]
Implement `go-service-ocios` (OCI Object Storage)  by https://github.com/oracle/oci-go-sdk

**Comment by Xuanwo** [comment]
@burntcarrot Hi, if you are interested in this project, we are willing to guide you through the whole issue. We believe it's a good start for you to get deeper into our projects.

**Comment by burntcarrot** [comment]
Thanks for the guidance! I believe I should need to get a better understanding of `go-storage` first before I could dive deep into services, because without understanding `go-storage`, I don't think it's possible for me to implement services.

I'm also not familiar with Oracle Cloud Storage and its SDK. I'll try my best to get an overview of how everything works, but as a student I can only dedicate limited time to this project.

Feel free to assign this to someone else! 😀

**Comment by xxchan** [comment]
@burntcarrot Actually you can learn by doing, and be confident! You are always welcome :p

**Comment by burntcarrot** [comment]
I would love to try but currently I'm trying to document about how each component works in `go-storage`. There is so much code to read, it's a bit difficult to understand such a huge project. 

I will write some blog posts describing about `go-storage` and its components in the future. I have limited experience in Go and in this project as well, but you have made me interested in working on this project. Thanks for being so helpful to the community! ♥

**Comment by Xuanwo** [comment]
> I would like to start with something simple, like the ISO service, etc.

I think ISO is much more complex than services like oracle cloud storage, because they are not normal storage services.

As @xxchan said, It's not hard to implement a service, we can start from [go-service-example](https://github.com/beyondstorage/go-service-example). Here are some docs about [implement services](https://beyondstorage.io/docs/go-storage/internal/implement-services), welcome for a read.

Oracle Cloud Storage's API looks like AWS S3, maybe you can take `go-service-s3` as references. And you can go our matrix room [go-storage](https://matrix.to/#/#go-storage:aos.dev) for help.

**Comment by Xuanwo** [comment]
I have set up the repo: https://github.com/beyondstorage/go-service-ocios

**Comment by burntcarrot** [comment]
The matrix chat is not available for me. I guess it's invite-only, my Matrix username is the same as the Github username.

And I guess we're going forward with usage of [`oci-go-sdk`](https://docs.oracle.com/en-us/iaas/tools/go/45.1.0/), right?

**Comment by Xuanwo** [comment]
> I guess it's invite-only

Something must be wrong, we will give it a look.

> my Matrix username is the same as the Github username.

I have invited you into the chat!

> And I guess we're going forward with the usage of [`oci-go-sdk`](https://docs.oracle.com/en-us/iaas/tools/go/45.1.0/), right?

Yep, I think so.

> What would you suggest the name to be used in `service.toml` and across the package?

I prefer `ocios` for now, and I'm open to your decisions. :laughing:

**Comment by Xuanwo** [comment]
@burntcarrot is busy working these days, so I unassigned this issue from him. Now, this issue is free for everyone.
