### ISSUE TITLE
NewStoragerFromString doesn't register service while initiating a new storager

### ISSUE THREAD

**Issue by burntcarrot** [beyondstorage/go-storage#694]
Calling `NewStoragerFromString` using a connection string with the value `fs:///tmp`, returns `ErrServiceNotRegistered`.

I'm using `go-service-fs/v3` as the go-storage service.

I found out that `ok`'s value is returned as `false`:
https://github.com/beyondstorage/go-storage/blob/d1451868532fd29cf90633f65b607eb9ef6e472b/services/new.go#L64-L68

Although `ty` is logged as `fs` in the error below, I think `fs` is not getting registered as a key in `storagerFnMap`, due to some issue in `RegisterStorager()`.

**Error Returned:**
```
2021/07/25 21:08:35 service init failed: fs new_storager: []: service not registered
exit status 1
```

**Code for reproducing the same error:**
```
package main

import (
    "bytes"
    "log"

    "github.com/beyondstorage/go-storage/v4/pairs"
    "github.com/beyondstorage/go-service-fs/v3"
)

func main() {
    // Init a service. Fails to the register the service here.
    store, err := services.NewStoragerFromString("fs:///tmp")
    if err != nil {
        log.Fatalf("service init failed: %v", err)
    }

    content := []byte("Hello, world!")
    length := int64(len(content))
    r := bytes.NewReader(content)

    _, err = store.Write("hello", r, length)
    if err != nil {
        log.Fatalf("write failed: %v", err)
    }

    var buf bytes.Buffer

    _, err = store.Read("hello", &buf)
    if err != nil {
        log.Fatalf("storager read: %v", err)
    }

    log.Printf("%s", buf.String())
}
```

**Comment by xxchan** [comment]
Try
```go
import (
	_ "github.com/beyondstorage/go-service-fs/v3"
)
```

I guess your IDE removed the unused import for you.

**Comment by burntcarrot** [comment]
Thanks! It worked.

What can we do in order to implement a fix for this? I don't see it suitable to import it like this, because people will depend on the widely-used go tooling suite provided by the Go extension in VSCode.

**Comment by burntcarrot** [comment]
We should also fix the quick start example in the [go-storage docs](https://beyondstorage.io/docs/go-storage/index).

The new example should be reflecting the changes like these:
```
import (
    "bytes"
    "log"

    "github.com/beyondstorage/go-storage/v4/pairs"
    _ "github.com/beyondstorage/go-service-fs/v3"
)
```

instead of:

```
import (
    "bytes"
    "log"

    "github.com/beyondstorage/go-storage/v4/pairs"
    "github.com/beyondstorage/go-service-fs/v3"
)
```

**Comment by xxchan** [comment]
> What can we do in order to implement a fix for this? I don't see it suitable to import it like this

I think it is a common practice in golang to use `import _` for importing a package purely for its initialization side effects (and I don't very like it), e.g., standard library `img`, `database/sql` uses it. 
https://stackoverflow.com/questions/26972615/a-use-case-for-importing-with-blank-identifier-in-golang

> We should also fix the quick start example in the go-storage docs. 

Thank you for reporting this problem. The docs are wrong, while the example in the [README](https://github.com/beyondstorage/go-storage#examples) is OK (They are out of sync! https://github.com/beyondstorage/site/issues/145)

**Comment by burntcarrot** [comment]
Ah, that's actually understandable as without a blank identifier, the `init` function wouldn't have been called.

Since the `init` function has the initialization for `RegisterStorager()` and `RegisterServicer()`, it might have caused the error to raise in my example. Thanks for pointing that out, this was a great learning experience!

And thanks for letting me know that the docs are out of sync.

**Comment by Xuanwo** [comment]
Closed for problem solved.
