### ISSUE TITLE
How to pass `partIndex` to `QuerySignHTTP` for `WriteMultipart`?

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#726]
s3 supports `presigned` for multipart uplaod. For the current `QuerySignHTTP`, seems there is no suitable way to pass in `partIndex` parameter:

```go
func (s *Storage) QuerySignHTTP(op string, path string, expire time.Duration, pairs ...Pair) (req *http.Request, err error) {}
```

**Alternative Way**

Add `index` system pair then use `pairs.WithIndex()` to pass in `partIndex` for `WriteMultipart`.

**Drawback**

All similar operations need to add extra pairs.

**Comment by Xuanwo** [comment]
Hi, @JinnyYi , can you migrate this discussion to https://forum.beyondstorage.io?

**Comment by JinnyYi** [comment]
> Hi, @JinnyYi , can you migrate this discussion to https://forum.beyondstorage.io?

Moved to https://forum.beyondstorage.io/t/how-to-pass-partindex-into-querysignhttp-for-writemultipart/192.
