### ISSUE TITLE
use path to append data

### ISSUE THREAD

**Issue by xiongjiwei** [beyondstorage/go-storage#733]
for now `WriteAppend` needs the object which will append to, is it possible to use the path? something like 
```go
WriteAppend(path string, r io.Reader, size int64, pairs ...Pair) (n int64, err error)
```

**Comment by JinnyYi** [comment]
- For object storage like oss, an appendable object is readable, users can perform the `AppendObject` operation to create an appendable object or append data to an existing object. So `use path to append data` may seem reasonable at first glance, but users should maintain the `append-offset`. 
- Service like dropbox needs a `start` operation to start an append process and a `finish` operation to mark this appends process has been finished. And before the `finish` has been called, the object is not readable for user. If `use path to append data`, users have to upload all the data at once and cannot append anymore.

So for go-storage, `Appender` is not a single operation like `WriteAppend` and we use `Object` to maintain some information for the append object. Ref:
- [Appender Introduction](https://beyondstorage.io/docs/go-storage/operations/appender/index)
- [GSP-44: Add CommitAppend in Appender](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/44-commit-append.md)

**Comment by Xuanwo** [comment]
Closed for no more comments. Please feel free to reopen it!
