### ISSUE TITLE
1st Cleanup Week: Service Integration Tests

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#745]
We have changed our integration test framework:

- For open source storage services (like hdfs, minio): we will run in the github actions directly.
- For other storage services (like s3, gcs, azblob): we will run in the https://teamcity.beyondstorage.io/overview

So we need to do following changes:

- Remove the GitHub integration tests file
- Add tests in teamcity, please ping @Xuanwo to finish.
- Replace the links for integration test baget.

**Please leave a comment if you want to take a part!**

## Services

- [x] go-service-hdfs
- [x] go-service-azblob
- [x] go-service-oss
- [x] go-service-ftp
- [x] go-service-kodo
- [x] go-service-qingstor
- [x] go-service-gcs
- [x] go-service-dropbox
- [ ] go-service-azfile
- [ ] go-service-s3
- [x] go-service-cos
- [ ] go-service-memory
- [ ] go-service-onedrive
- [x] go-service-bos
- [ ] go-service-zip
- [x] go-service-obs
- [ ] go-service-us3
- [ ] go-service-ocios
- [ ] go-service-example
- [ ] go-service-uss
- [ ] go-service-webdav
- [ ] go-service-fs
- [ ] go-service-storj
- [ ] go-service-gdrive
- [ ] go-service-minio
- [ ] go-service-ipfs
- [ ] go-service-tar

**Comment by abyss-w** [comment]
The services that have been cleaned are:
- [go-service-azblob](https://github.com/beyondstorage/go-service-azblob/pull/50)
- [go-service-oss](https://github.com/beyondstorage/go-service-oss/pull/54)
- [go-service-kodo](https://github.com/beyondstorage/go-service-kodo/pull/53)
- [go-service-qingstor](https://github.com/beyondstorage/go-service-qingstor/pull/90)
- [go-service-gcs](https://github.com/beyondstorage/go-service-gcs/pull/67)
- [go-service-cos](https://github.com/beyondstorage/go-service-cos/pull/57)
- [go-service-bos](https://github.com/beyondstorage/go-service-bos/pull/8)
- [go-service-obs](https://github.com/beyondstorage/go-service-obs/pull/7)
