### ISSUE TITLE
getAbsPath in service works poorly 

### ISSUE THREAD

**Issue by junaire** [beyondstorage/go-storage#753]
I found there is something wrong with our current `getAbsPath` implementation:
- Why it just simply splice `workDir` and `path` without `/` ?
- It doesn't check the input, so it might splice `workDir` and absolute path again, which means it can be easily misused.

![image](https://user-images.githubusercontent.com/77525145/133043166-82e6d719-6285-49d6-849c-a7c879e3e079.png)

Is there anything wrong with `getRelPath` too?

**Comment by Xuanwo** [comment]
`getAbsPath` and `getRelPath` are designed to be implemented by the service itself. Maybe the problem is introduced by borrowing code from other services directly? It's OK to refactor `getAbsPath` and `getRelPath`.

**Comment by junaire** [comment]
> `getAbsPath` and `getRelPath` are designed to be implemented by the service itself. Maybe the problem is introduced by borrowing code from other services directly? It's OK to refactor `getAbsPath` and `getRelPath`.

Got it.
