### ISSUE TITLE
Compilation fails if `Default*Pairs` unimplemented in service

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#760]
### What happened?

A compilation error occured when service does not implement `Default*Pairs`:

```shell
vet: ./generated.go:145:10: result.HasDefaultStoragePairs undefined (type pairStorageNew has no field or method HasDefaultStoragePairs)
```

ref: https://github.com/beyondstorage/go-service-example/runs/3497258311?check_suite_focus=true

### Version

4.7.0

**Comment by Xuanwo** [comment]
Let's fix this problem in this sprint: https://github.com/beyondstorage/community/issues/48
