### ISSUE TITLE
Integration test fails with Dropbox v2 api error `too_many_write_operations`

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#893]
ref: https://teamcity.beyondstorage.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=878&_focus=237

**Comment by Xuanwo** [comment]
Test local could be successful. Let's try to don't run integration tests at the same time.

**Comment by Xuanwo** [comment]
We will support rate limit error in the further.
