### ISSUE TITLE
Tracking issue of services tests

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#920]
## No Test Account

- [ ] https://github.com/beyondstorage/go-storage/issues/918
- [ ] #923

## Not Stable

- [ ] https://github.com/beyondstorage/go-storage/issues/906

**Comment by Joey-1445601153** [comment]
## No Test Account
> * [ ]  [services/onedrive: Integration tests failed because of lacking onedrive test account. #923](https://github.com/beyondstorage/go-storage/issues/923)

**Comment by Xuanwo** [comment]
Use https://github.com/beyondstorage/go-storage/issues/536 to track instead.
