### ISSUE TITLE
services/s3: `List` with `types.ListModePart` mode test fails when using MinIO

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-storage#924]
`services/s3` should compatible with `MinIO` and pass integration test with `MinIO`:  `List` with `types.ListModePart` mode should lists in-progress multipart uploads.

1. `CreateMultipart` with key `420d60bd-c35a-4106-a347-4eaeaef5276e/6ed57725-4f94-4cf2-b2eb-81a857a1a3e3`: get the `MultipartID`: `dbacfbb1-5c55-43a9-aeac-ba0c39521c9e`
2. `WriteMultipart` with the `MultipartID` get from step 1 to write a part
3. `List` with `types.ListModePart` mode to get the iterator `it`.

## Excepted Behavior

We can retrieve all the in-progress multipart uploads by calling `Next()` continuously until get the `IterateDone`.
```
mo, err := it.Next()
mid, ok := mo.GetMultipartID()
// mid should equal to the `MultipartID` returned by `CreateMultipart`
```

## Current Behavior

When calling `it.Next()`:
```
runtime error: invalid memory address or nil pointer dereference
```

The `ListMultipartUploads` request and response are as follows, no in-progress mulitpart upload info in the response body:

![image](https://user-images.githubusercontent.com/82445294/138200191-b74066e4-ebc6-420a-b170-1bf1c64d8d0b.png)

## Steps to Reproduce

Run integration test for services/s3 with the following config:

```
STORAGE_S3_INTEGRATION_TEST=on
STORAGE_S3_CREDENTIAL=hmac:admin:password
STORAGE_S3_NAME=<bucketname>
STORAGE_S3_LOCATION=local
```

Also we need to set `endpoint` and `UsePathStyle` for initialization:
```go
pairs.WithEndpoint("http:<MinIO server IP>:9000")
s3.WithForcePathStyle()
````

## Environment

- MinIO: minio version RELEASE.2021-10-13T00-23-17Z
- services/s3: v2.5.0

**Comment by JinnyYi** [comment]
Possible answer: https://github.com/minio/minio/issues/11686

**Comment by Xuanwo** [comment]
I think the problem should be https://github.com/beyondstorage/go-storage/issues/1000
