### ISSUE TITLE
services/s3: Add tests that upon minio

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#938]
## Decription

minio is a widely used s3 compatible service, it could be nice if we run integration tests upon minio everything we have a change on services s3.

This could also avoid problems like https://github.com/beyondstorage/go-storage/issues/860#issuecomment-947460878

## Solution

Add a new job under https://github.com/beyondstorage/go-storage/blob/master/.github/workflows/services-test-s3.yml.

The content may be similar with https://github.com/beyondstorage/go-storage/blob/master/.github/workflows/services-test-minio.yml

**Comment by Xuanwo** [comment]
ping @Joey-1445601153, can you help solving this problem?

**Comment by Joey-1445601153** [comment]
> ping @Joey-1445601153, can you help solving this problem? We need to solve #924 before.

Yes. We can use #1000  to solve the problem #924.  And I checked your [last PR](https://github.com/beyondstorage/go-storage/pull/999). Maybe we lost a location in the new job .
