### ISSUE TITLE
Tracking issue of GSP-970: Service Factory

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-storage#975]
- GSP: https://github.com/beyondstorage/go-storage/pull/970

## Steps

- [x] https://github.com/beyondstorage/go-storage/pull/976
- [ ] Generate factory in serivces

**Comment by Xuanwo** [comment]
The definitions have been refactored, we can build factory now.

**Comment by Xuanwo** [comment]
Let's migrate all services to factory! @Joey2132, take https://github.com/beyondstorage/go-storage/pull/997 as reference.

**Comment by Joey2132** [comment]
> migrate all services to factory! @Joey2132, take #997 as refe



> Let's migrate all services to factory! @Joey2132, take #997 as reference.

Got it. Maybe we should list all services like issue #868 does?

**Comment by Xuanwo** [comment]
Updated.

**Comment by Joey2132** [comment]
> Updated.

Got it. After adding test upon minio for s3, I will start to handle it.

**Comment by Xuanwo** [comment]
@Joey2132 How about creating a comment yourself so that you can maintain the working progress?

**Comment by Joey2132** [comment]
> How about creating a comment yourself so that you can maintain the working progress?

Yes. In this way, I can update it by myself. So please delete it in your description. I will create another one.

**Comment by Joey2132** [comment]
## Current progress

 * [ ]  azblob
 * [ ]  bos
 * [ ]  cos
 * [ ]  dropbox
 * [ ]  example
 * [ ]  fs
 * [ ]  ftp
 * [ ]  gcs
 * [ ]  gdrive
 * [ ]  hdfs
 * [ ]  ipfs
 * [ ]  kodo
 * [ ]  memory
 * [ ]  minio
 * [ ]  obs
 * [ ]  onedrive
 * [ ]  oss
 * [ ]  qingstor
 * [ ]  s3
 * [ ]  storj
 * [ ]  tar
 * [ ]  uss
 * [ ]  webdav
 * [ ]  zip
